### ISSUE TITLE
ili9488 + stm32f103ret6

### ISSUE THREAD

**Issue by clear-sky** [RobertoBenjami/stm32_graphics_display_drivers#1]
hi 
thanks for your great work for beginners(as me!)
i am trying to run ili9488 on f103re(8 bit parallel) with your youtube film but no success
i think you have forgotten to add setup pin configurations (gpio output on video)
this is my setup
d0-d7 > pin c0 to c7
rd > pin c8
wr > pin c9
cs > pin c10
rs > pin c11
rst > pin c12
i set all pins as out put except c8 (it is input)
compile give me no error but no success in action
i use stm32cube ide in linuxmint

**Comment by RobertoBenjami** [comment]
Hi!
8bit paralell mode video: https://www.youtube.com/watch?v=2oP4vGotuJA&feature=youtu.be
