### ISSUE TITLE
Support for stm32h7 + OTM8009A

### ISSUE THREAD

**Issue by flangela** [RobertoBenjami/stm32_graphics_display_drivers#10]
if possible please support stm32h7 fsmc in 16 bit mode and OTM8009A LCD IC
i want use stm32h743vit6 and this LCD: http://www.lcdwiki.com/3.97inch_16BIT_Module_OTM8009A_SKU:MRB3971

**Comment by RobertoBenjami** [comment]
I'm sorry, but I don't have a display like this. According to its data sheet, it is very similar to ILI9341. Transform this. If you get stuck write here, I'll try to help.
