### ISSUE TITLE
Horizontal display with good viewing angles - 480x272 SSD1963?

### ISSUE THREAD

**Issue by JuMalIO** [RobertoBenjami/stm32_graphics_display_drivers#11]
Hi, just wanted to ask if you know any horizontal display with good viewing angles?

I have bought this [ILI9486 320x480 3.5inch_Arduino_Display-UNO](http://www.lcdwiki.com/3.5inch_Arduino_Display-UNO) but I think this display is not intended to be used in horizontal orientation 480x320, I was really disappointed, its horizontal viewing angles are horrible.

What about SSD1963 480x272? I think its for horizontal use, is there any plans to support its drivers?

**Comment by RobertoBenjami** [comment]
Perhaps IPS type displays have a wider viewing angle. You may also want to check out the displays for RPI.

**Comment by JuMalIO** [comment]
And what about SSD1963 (480x272), do you have any plans to add that? Or ILI9806G (480x854)? Or they are too different?

**Comment by jmalStorm** [comment]
I have also found DWIN DGUS Smart Display display, which are IPS, high resolution and quite cheap. They seem to be very fast, but I don't really like that I wont be able to do low level coding on it... Would love to see them hacked for low level application...

**Comment by RobertoBenjami** [comment]
I don't know these displays. Larger displays are already expensive. If I need one, I'd rather use an old 15 'or 17' monitor with an analog VGA connector. They are easy to operate with LTDC capable controllers.
