### ISSUE TITLE
3.5inch Arduino Display-Mega2560?

### ISSUE THREAD

**Issue by JuMalIO** [RobertoBenjami/stm32_graphics_display_drivers#12]
Hi, I want to power this [3.5inch Arduino Display-Mega2560](http://www.lcdwiki.com/3.5inch_Arduino_Display-Mega2560) from STM32F407VE, but cant find RD and backlight pin on the display? Also it writes that its 5V, but in your PDF i see that you use 3.3V?
How do I connect this display?
![](http://www.lcdwiki.com/images/5/5f/MAR3513-001.png)

**Comment by JuMalIO** [comment]
Seems to work without RD pin and with 5V.

**Comment by RobertoBenjami** [comment]
I haven't seen a display without an RD pin yet, but I'll modify the GPIO8 and GPIO16 driver to make the RD pin optional.
