### ISSUE TITLE
Support for STM32L4xx 16 bit for ILI9341

### ISSUE THREAD

**Issue by BarbaraTom94** [RobertoBenjami/stm32_graphics_display_drivers#14]
Hi! Great job!! Your library is great! Do you have any plan of releasing the 16 bit version for STM32L4xx boards??
Thank you

**Comment by RobertoBenjami** [comment]
Originally, no types L0, L1, L4 were designed (because I don't have such a controller), but it wasn't too much work to rewrite from types F0, F1, F4. If I have some time, I'll rewrite the GPIO16, but unfortunately I can't test it.

**Comment by BarbaraTom94** [comment]
Thank you Roberto!!
