### ISSUE TITLE
ILI9881C driver

### ISSUE THREAD

**Issue by Honza123321** [RobertoBenjami/stm32_graphics_display_drivers#16]
Hi,

I am working on display for electric motorcycle.  

I have STM32F769i-Discovery and [WF50DSYA3MNN0]( https://www.winstar.com.tw/products/tft-lcd/ips-tft/720x1280.html). 
This display has ILI9881C driver. I have connected display and kit through converter board. 

I find out your drivers for ili9486, ili9488,... 
I would to ask, if there is posibilty modify this code and use it for ILI9881C driver. 

Thanks for your advice.
Best regards Honza.

**Comment by RobertoBenjami** [comment]
Unfortunately, I do not have such a display. I don't have a MIPI DSI interface in any of my controllers. The https://github.com/RobertoBenjami/stm32_vga driver may need to be modified to work with it. Be sure to add external SDRAM memory to the framebuffer (720x1280x16bit/pixel = 1.85MB).
