### ISSUE TITLE
Help with ILI9486 - SPI mode.

### ISSUE THREAD

**Issue by Nicolaspardo** [RobertoBenjami/stm32_graphics_display_drivers#17]
Hi! 

I can use this library for comunicate stm32f103c8 with a SPI LCD 3.5" for RPi. My display is similar like that : "http://www.lcdwiki.com/3.5inch_RPi_Display ". 
As i can see the driver is ili9486. I tryed it with an example with Standard Peripheral Library , but not HAL.
I followed all the steps in this instructions and compiling the code works well. But i cant see image. I change the pins, and the macros in "lcd_io_spi.h" but nothing...

Can you help me?

I use this guide shared in your website
(https://www.youtube.com/watch?v=4NZ1VwuQWhw)
stm32f103c8 (bluepill board) - st7735 spi driver

Great work !
Tks

**Comment by RobertoBenjami** [comment]
Unfortunately I don't have an ili9486 display. I only have ili9488 display and it is very different from parallel and spi version. Try the ili9488 driver set to SPI mode.
