### ISSUE TITLE
ILI9341 in SPI mode tested on L152RE

### ISSUE THREAD

**Issue by GunterO** [RobertoBenjami/stm32_graphics_display_drivers#23]
Hi, 
Your README.md says "untested", but I tested your code on a L152RE board (Nucleo) in combination with an ILI9341 LCD, and this is working perfect (software SPI, hardware SPI & hardware SPI with DMA).
I used the STM32CubeIDE instead of TrueStudio, but your walk-through applied quite well on this IDE.
Thanks!

**Comment by RobertoBenjami** [comment]
Thank you for the test.
