### ISSUE TITLE
Please add support for display SSD1963

### ISSUE THREAD

**Issue by vailatis** [RobertoBenjami/stm32_graphics_display_drivers#31]
Hi, i'm trying to add support for display SSD1963 (800x480 7" display).
I've copied the initialization commands sequence from another library that is working, but i'm just getting the display to initialize, startup and show something (like clear screen and draw a cirle) display a blue rectangle in the center of the screen with some sorta of circle all messed up.
I have this display, so if you wanna try with my help to create this driver support, i'll be glad to contribute.

I attach here the code i've created for this display, if wanna check it:
[ssd1963.zip](https://github.com/RobertoBenjami/stm32_graphics_display_drivers/files/8032049/ssd1963.zip)

**Comment by RobertoBenjami** [comment]
All right. Can you show a picture or video of what you do?
