### ISSUE TITLE
ili9328 tft lcd Touch not working

### ISSUE THREAD

**Issue by Deepakkumarji** [RobertoBenjami/stm32_graphics_display_drivers#35]
when i use ili9328 tft lcd with arduino uno code then ili9328 tft lcd touch is working fine. 
With stm32f103vbt6 microcontroller & ili9328 tft lcd, i am using lcdts_io_gpio8 file to parallel communicate with microcontroller with application TouchCalib  . normal lcd print is working fine but touch is not working. Please help me to resolve this problem. I am also attaching the file......
[STM32F103VBT6 WITH ILI9328 WITH ATOLIC TRUE STUDIO 2 18-08-2022 REV1.zip](https://github.com/RobertoBenjami/stm32_graphics_display_drivers/files/9372011/STM32F103VBT6.WITH.ILI9328.WITH.ATOLIC.TRUE.STUDIO.2.18-08-2022.REV1.zip)
. My email id is Deepak.k@upsinverter.com

**Comment by RobertoBenjami** [comment]
Add the breakpoint at ili9328.c line 695. See the x1, x2, y1, y2 local variables. Is it related to at which point we touch the screen?
