### ISSUE TITLE
SPFD5408/ILI932x

### ISSUE THREAD

**Issue by freetoair** [RobertoBenjami/stm32_graphics_display_drivers#38]
Namely, in fsmc mode 8bit with the SPFD 5408 controller, I can't get a display on the screen, only a white screen, no image. This controller in the sequence to write the index register does not need to write the higher byte, only the low uint8_t byte, could it be a problem or the speed of the transaction?  
    To be precise, the controller in that lcd has ID = 2053, but it works fine with drivers for ILI932x. It is otherwise a very common LCD Arduino shield.
Just one more observation that might help solve the problem:
At the moment when he needs to write something in GRAM, the screen is completely white, but in between for a moment color noise appears. That's why I thought that the problem might be with the speed of writing in GRAM.
regards, freetoair

**Comment by RobertoBenjami** [comment]
I don't have such an LCD.
FSMC speed settings is possible in CubeMX or CubeIDE (clock cycles parameters).
