### ISSUE TITLE
Touch support for ili9341?

### ISSUE THREAD

**Issue by yuanyanhui** [RobertoBenjami/stm32_graphics_display_drivers#4]
It seems there is no touch support for  ili9341. I tried to use appPaint with ili9341 and found there are no ts_drv and ts_cindex definitions.

**Comment by RobertoBenjami** [comment]
I Updated the driver, but I can't tested (I have not a 8 bits paralell ili9341 display with touch). Please first step is the appTouchCalib.

**Comment by yuanyanhui** [comment]
My display is different from Adafruit's which has X-/+, Y-/+ pins exposed. The touch controller of my display use SPI connection. Does this mean I cannot use the touch support in your library?

**Comment by RobertoBenjami** [comment]
I put the touchscreen on the paralell 8bit, because they are in common pins with the display control and therefore cannot be separated. 
What kind of display is it?

**Comment by yuanyanhui** [comment]
![image](https://user-images.githubusercontent.com/51470109/75607299-92f04880-5b30-11ea-9880-ac51de2af2ae.png)
![image](https://user-images.githubusercontent.com/51470109/75607323-cfbc3f80-5b30-11ea-90be-444248796827.png)

The touch controller IC is XPT2046. 
![image](https://user-images.githubusercontent.com/51470109/75607417-dd25f980-5b31-11ea-9d5b-a2eb8b7fe1df.png)

**Comment by RobertoBenjami** [comment]
Since this touchscreen is independent of the display controls, any xpt2046 driver can be used. But if I have time, I'll check it out because I have this touch chip on one of my displays.

**Comment by Rajssss** [comment]
@yuanyanhui I have a similar module, I am trying to make it work but the display shows nothing, no backlight too. When I pull the LEDA pin to 3.3V the backlight did work but still nothing on the display.

**Comment by RobertoBenjami** [comment]
Since then, the standalone xpt2046 driver has been completed.
