### ISSUE TITLE
how to draw a string on ILI9488 screen?

### ISSUE THREAD

**Issue by gengyatong** [RobertoBenjami/stm32_graphics_display_drivers#41]
hello, thank you for your hard work!
i want to konw  how to draw a string on a ILI9488 screen? is there any function to do this ? should i write these function myself ?

**Comment by RobertoBenjami** [comment]
Example:
`BSP_LCD_DisplayStringAt(10, 10, (uint8_t *)"String test", LEFT_MODE);`
