### ISSUE TITLE
using LCD_IO_WriteCmd8MultipleData16 for each image row

### ISSUE THREAD

**Issue by JuMalIO** [RobertoBenjami/stm32_graphics_display_drivers#7]
Would it be possible to expose these functions:

    ili9341_SetDisplayWindow(Xpos, Ypos, Xsize, Ysize);
    LCD_IO_WriteCmd8MultipleData16(ILI9341_RAMWR, (uint16_t *)pData, Xsize * Ysize);

So it would be possible to send each row of image without calling ili9341_SetDisplayWindow?

    ili9341_SetDisplayWindow(Xpos, Ypos, Xsize, Ysize);
    for (int i = 0; i < image_height; i++)
    {
      // read image line
      LCD_IO_WriteCmd8MultipleData16(ILI9341_RAMWR, (uint16_t *)pData, Xsize * Ysize);
    }

Just interested to see would it improve performance. I am trying to make screen as fast as possible...

**Comment by RobertoBenjami** [comment]
Try this:
`#define ILI9341_RAMWRCONT       0x3C
ili9341_SetDisplayWindow(Xpos, Ypos, Xsize, Ysize);
for (int i = 0; i < image_height; i++)
{
  // read image line
  if(!i)
    LCD_IO_WriteCmd8MultipleData16(ILI9341_RAMWR, (uint16_t *)pData, Xsize * Ysize);
  else
    LCD_IO_WriteCmd8MultipleData16(ILI9341_RAMWRCONT, (uint16_t *)pData, Xsize * Ysize);
}`

**Comment by JuMalIO** [comment]
Its amazing thank you again!
